### ISSUE TITLE
Python error when importing CS:GO model

### ISSUE THREAD

**Issue by TolyaArzamas** [lasa01/io_import_vmf#102]
Im new to Blender and don't know how to fix this problem. I have blender 3.0, blender source tools and this addon. I can't import player models from CS:GO. Everytime I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\__init__.py", line 1123, in execute
    qc_importer.get(name, context.collection, context)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\import_qc.py", line 404, in get
    return self.get_smd(name, collection, context).a
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\import_qc.py", line 390, in get_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model hostage_varianta hasn't been imported

location: <unknown location>:-1

What am I doing wrong?

**Comment by lasa01** [comment]
Please post full logs. That error is caused by another error, which should be in the logs if you scroll up.
