### ISSUE TITLE
Error after 

### ISSUE THREAD

**Issue by clg236** [lasa01/io_import_vmf#104]
Hi! Using Blender 3.0, everything appears to be set up correctly, but getting the following error when importing:

`Python: Traceback (most recent call last):
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\__init__.py", line 747, in execute
    with importer:
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\import_vmf.py", line 124, in __enter__
    self._qc_importer.__enter__()
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\import_qc.py", line 197, in __enter__
    bpy.utils.unregister_class(import_smd.SmdImporter)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

location: <unknown location>:-1`

**Comment by lasa01** [comment]
Seems like you forgot to enable Blender Source Tools in the preferences. In
addition to installing it you need to also tick the checkbox next to it's
name in preferences to enable it.

**Comment by lasa01** [comment]
Closing due to inactivity.
