### ISSUE TITLE
Cannot build module on linux.

### ISSUE THREAD

**Issue by superyu1337** [lasa01/io_import_vmf#105]
**Describe the bug**
Module 'vdf' cannot compile.

**To Reproduce**
Running ./install.sh

**Expected behavior**
Module 'vdf' compiles and can be used.

**Logs (From my terminal)**
```
io_import_vmf on  master [!] via 🐍 v3.10.1 took 4s 
❯ pip install -t ./io_import_vmf/deps -r requirements.txt
Collecting vmfpy
  Cloning https://github.com/lasa01/vmfpy.git to /tmp/pip-install-bwdickwi/vmfpy_44289cc97ad54c8ca5b05f60ec262bec
  Running command git clone -q https://github.com/lasa01/vmfpy.git /tmp/pip-install-bwdickwi/vmfpy_44289cc97ad54c8ca5b05f60ec262bec
Collecting pyvtflib
  Cloning https://github.com/lasa01/pyvtflib.git to /tmp/pip-install-bwdickwi/pyvtflib_32798fadb71249188d294ffca99dcb30
  Running command git clone -q https://github.com/lasa01/pyvtflib.git /tmp/pip-install-bwdickwi/pyvtflib_32798fadb71249188d294ffca99dcb30
Collecting vdf@ git+https://github.com/lasa01/vdf.git#egg=vdf
  Cloning https://github.com/lasa01/vdf.git to /tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044
  Running command git clone -q https://github.com/lasa01/vdf.git /tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vghql6_t
         cwd: /tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/setup.py", line 6, in <module>
        import vdf
      File "/tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/vdf/__init__.py", line 19, in <module>
        from vdf.vdict import VDFDict
      File "/tmp/pip-install-bwdickwi/vdf_6b1abc57d971493caa87d23f126ce044/vdf/vdict.py", line 9, in <module>
        class _kView(_c.KeysView):
    AttributeError: module 'collections' has no attribute 'KeysView'
    ----------------------------------------
WARNING: Discarding git+https://github.com/lasa01/vdf.git#egg=vdf. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
INFO: pip is looking at multiple versions of pyvtflib to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement vdf (unavailable) (from vmfpy)
ERROR: No matching distribution found for vdf (unavailable)
```

**Details (please complete the following information):**
 - OS: Linux (5.15.2)
 - Python version: 3.10.1
 - Addon Version: github-master branch
 - Did you download a release or build the addon yourself: building myself
 
 Interesting is, that I get the same error when trying to enable the module from a release package in blender.
 `AttributeError: module 'collections' has no attribute 'KeysView`

**Comment by lasa01** [comment]
Looks like my vdf fork is not compatible with latest python. It seems to be fixed in the original repo, and since my PR has been merged I switched the dependency to the original repo. So this should be fixed now.
