### ISSUE TITLE
Error import map black mesa 

### ISSUE THREAD

**Issue by batomot** [lasa01/io_import_vmf#108]
Error import map game black mesa. 
Log: Traceback (most recent call last):
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\__init__.py", line 718, in execute
    fs = self.get_filesystem(context)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\__init__.py", line 475, in get_filesystem
    return game_def.get_indexed_filesystem()
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\__init__.py", line 270, in get_indexed_filesystem
    fs_dict[self.name] = VMFFileSystem(data_dirs, data_paks, index_files=True)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 82, in __init__
    self.index_all()
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 150, in index_all
    self._do_index(self.iter_all())
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 124, in _do_index
    for path, info in index_iter:
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 121, in iter_all
    yield from self.iter_paks()
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 117, in iter_paks
    yield from self.iter_pak(pak_file)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 110, in iter_pak
    pak = vpk.open(pak_file)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 16, in open
    return VPK(*args, **kwargs)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 207, in __init__
    self.read_header()
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 309, in read_header
    raise ValueError("File is not VPK (invalid magic)")
ValueError: File is not VPK (invalid magic)

location: <unknown location>:-1

**Comment by lasa01** [comment]
Seems like the game configuration is incorrect. Make sure there are no vpk files with numbered suffixes (eg. pak01_001.vpk) in the vpk files section, instead only put the files with _dir.vpk suffix there. Also, wildcard directories should probably be empty.

**Comment by batomot** [comment]
There are no numbered files in my files. vmf files are numbered only. 
![Без имени](https://user-images.githubusercontent.com/36561633/149574536-ce6e78fa-0940-4c0f-a7a2-4ef6b16b57e6.jpg)

**Comment by batomot** [comment]
I tried to remove the numbering of vmf files and still this error pops up

**Comment by batomot** [comment]
And changing the blender version did not help. I changed the version to 2.90 and the error is the same there

**Comment by batomot** [comment]
Problem solved. Solution to the problem: remove the numbering of all files in the directories of the root of the game and directories of unpacked maps
