### ISSUE TITLE
Error import. 

### ISSUE THREAD

**Issue by batomot** [lasa01/io_import_vmf#109]
Error log: Python: Traceback (most recent call last):
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 72, in _parse_int
    return int(value)
ValueError: invalid literal for int() with base 10: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\__init__.py", line 748, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\import_vmf.py", line 140, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 785, in __init__
    entity_inst = self._parse_custom(VMFPropEntity, "entity (prop)", entity, self.fs)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 282, in __init__
    self.skin = self._parse_int_str("skin", data)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 78, in _parse_int_str
    return self._parse_int(name, value)
  File "C:\Users\vttet\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 74, in _parse_int
    raise VMFParseException(f"{name} is not a valid int", self._context)
vmfpy.VMFParseException: VMF parsing failed: entity (prop) (id 51990) skin is not a valid int

location: <unknown location>:-1

Almost all VMF files are imported, but on some I get this error. 
In the screenshot, the source file due to which the error occurs
![2](https://user-images.githubusercontent.com/36561633/149632238-dd353aae-3367-4e96-9ef5-5073800e7439.png)

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
