### ISSUE TITLE
Black Mesa maps don't import

### ISSUE THREAD

**Issue by jkerman2000** [lasa01/io_import_vmf#111]
Blender Version: 3.0

Log:

Python: Traceback (most recent call last):
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\__init__.py", line 759, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\import_vmf.py", line 143, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 778, in __init__
    entity_inst = self._parse_custom(VMFLightEntity, "entity (light)", entity, self.fs)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 357, in __init__
    color, brightness = self._parse_custom_str(VMFColor.parse_with_brightness, "_lightHDR", data)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 145, in _parse_custom_str
    return self._parse_custom(parser, name, value)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 213, in parse_with_brightness
    raise VMFParseException("color with brightness doesn't have at least 3 values")
vmfpy.VMFParseException: VMF parsing failed: entity (light) (id 1657980) _lightHDR color with brightness doesn't have at least 3 values

location: <unknown location>:-1

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
