### ISSUE TITLE
VMFParseException: VMF parsing failed

### ISSUE THREAD

**Issue by HarryPlopper91** [lasa01/io_import_vmf#116]
**Describe the bug**
Trying to import a decompiled map from CS:GO, followed youtube video for install and setup. When you go to import file, the import fails and does not import anything into blender. 

**To Reproduce**
1. Decompile map as stated in YouTube video walkthrough
2. Open Blender, go to file import > Import VPF
3. Selected decompled VPF file

**Expected behavior**
Expected map import.

**Related files**
https://steamcommunity.com/sharedfiles/filedetails/?id=191701779

**Details (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 3.1.2
 - Addon Version: 
 - Did you download a release or build the addon yourself: downloaded a release
 - Related Game: CS:GO

**Logs**
```
[1/12] Parsing map...
Python: Traceback (most recent call last):
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\__init__.py", line 759, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\import_vmf.py", line 143, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 774, in __init__
    entity_inst = self._parse_custom(VMFSpotLightEntity, "entity (light_spot)", entity, self.fs)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 403, in __init__
    self.angles = self._parse_custom_str(VMFVector.parse_str, "angles", data)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 145, in _parse_custom_str
    return self._parse_custom(parser, name, value)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\bradl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 161, in parse_str
    raise VMFParseException("vector doesn't contain 3 values")
vmfpy.VMFParseException: VMF parsing failed: entity (light_spot) (id 384808) angles vector doesn't contain 3 values

location: <unknown location>:-1

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
