### ISSUE TITLE
Any map results in blender python error

### ISSUE THREAD

**Issue by irishgreencitrus** [lasa01/io_import_vmf#146]
**Describe the bug**
Tried importing decompiled maps from Portal 2, and anything results in this error.
I'm not experienced with Blender's python integration, but if you want me to do something, you can point me in the right direction and I'll happily make a PR.

**Logs**
```
Python: Traceback (most recent call last):
  File "/home/lime/.config/blender/3.3/scripts/addons/io_import_vmf/__init__.py", line 759, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "/home/lime/.config/blender/3.3/scripts/addons/io_import_vmf/import_vmf.py", line 180, in load
    self._vmt_importer.load_all()
  File "/home/lime/.config/blender/3.3/scripts/addons/io_import_vmf/import_vmt.py", line 1201, in load_all
    current = 0
    ^^^^^^^^^^^^
  File "/home/lime/.config/blender/3.3/scripts/addons/io_import_vmf/import_vtf.py", line 73, in load_all
    self._load(image_name, staged)
  File "/home/lime/.config/blender/3.3/scripts/addons/io_import_vmf/import_vtf.py", line 105, in _load
    image.colorspace_settings.name = staged.colorspace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('Linear', 'sRGB')
```
**Details (please complete the following information):**
 - OS: Void Linux
 - Blender Version: 3.3.0
 - Addon Version: 0.6.9
 - Did you download a release or build the addon yourself: Built from source
 - Related Game: Portal2

**Comment by irishgreencitrus** [comment]
My bad, I didn't realise there was a new branch
