### ISSUE TITLE
Some props have wrong rotation

### ISSUE THREAD

**Issue by DrPeeper228** [lasa01/io_import_vmf#149]
**Describe the bug**

**To Reproduce**
1. Import a 'sp_a3_column_blocker'(use vmf provided in Portal 2\sdk_content\maps)
2. Go to the left of the chamber from entarance
3. See error

**Expected behavior**
Panels should attach to walls, not to the air with wrong rotations

**Related files**
it is provided in Portal 2 Authoring Tools
**Logs**
```
Read prefs: C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Info: Deleted 3 object(s)

addon_utils.disable: io_scene_valvesource not disabled
Modules Installed (io_scene_valvesource) from 'C:\\Users\\Velton\\Downloads\\blender_source_tools_3.2.5.zip' into 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
addon_utils.disable: io_import_vmf not disabled
Modules Installed (io_import_vmf) from 'C:\\Users\\Velton\\Downloads\\io_import_vmf-windows.zip' into 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
reloading addon: io_import_vmf 1673674303.0202475 1673674384.9492424 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons\\io_import_vmf\\__init__.py'
Modules Installed () from 'C:\\Users\\Velton\\Downloads\\io_import_vmf-windows.zip' into 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
reloading addon: io_import_vmf 1673674384.9492424 1673674403.8426874 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons\\io_import_vmf\\__init__.py'
Modules Installed () from 'C:\\Users\\Velton\\Downloads\\io_import_vmf-windows.zip' into 'C:\\Users\\Velton\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
Writing userprefs: 'C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend' ok
Info: Preferences saved

Indexing game files...
Traceback (most recent call last):
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\__init__.py", line 728, in execute
    fs = self.get_filesystem(context)
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\__init__.py", line 475, in get_filesystem
    return game_def.get_indexed_filesystem()
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\__init__.py", line 270, in get_indexed_filesystem
    fs_dict[self.name] = VMFFileSystem(data_dirs, data_paks, index_files=True)
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 82, in __init__
    self.index_all()
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 150, in index_all
    self._do_index(self.iter_all())
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 124, in _do_index
    for path, info in index_iter:
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 121, in iter_all
    yield from self.iter_paks()
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 117, in iter_paks
    yield from self.iter_pak(pak_file)
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 110, in iter_pak
    pak = vpk.open(pak_file, path_enc="latin1")
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 16, in open
    return VPK(*args, **kwargs)
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 255, in __init__
    self.read_header()
  File "C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_import_vmf\deps\vpk\__init__.py", line 357, in read_header
    raise ValueError("File is not VPK (invalid magic)")
ValueError: File is not VPK (invalid magic)
Writing userprefs: 'C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend' ok
Info: Preferences saved

Indexing game files...
Indexing done in 4.246492385864258 s
Started importing VMF 'C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\sp_a2_column_blocker.vmf'
[1/12] Parsing map...
[2/12] Determining required game files...
[WARNING] UNSUPPORTED MATERIAL PARAMS: $ssbumpmathfix, $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002b
[WARNING] UNSUPPORTED MATERIAL PARAMS: $ssbumpmathfix, $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/black_wall_metal_005c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002d
[WARNING] UNSUPPORTED MATERIAL PARAMS: $ssbumpmathfix, $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/black_wall_metal_005b
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/black_wall_metal_005a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $vertexfog in metal/metalwall_bts_006a_cheap
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_floor_metal_001d
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_floor_metal_001c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/metalwall_bts_006a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $forceexpensive, $flowmap, $flow_normaluvscale, $flow_worlduvscale, $flow_timeintervalinseconds, $flow_uvscrolldistance, $flow_bumpstrength, $flow_noise_texture, $flow_noise_scale, $flow_debug, $color_flow_uvscale, $color_flow_timeintervalinseconds, $color_flow_uvscrolldistance, $color_flow_lerpexp, $color_flow_displacebynormalstrength, $reflecttexture, $reflectamount, $reflecttint, $reflectskyboxonly, $reflectonlymarkedentities, $abovewater, $bottommaterial, $fogstart, $fogend, $lightmapwaterfog, $flashlighttint in nature/toxicslime_a2_column_blocker
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in nature/dirtfloor004c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation in plastic/plasticwall004a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $nodecal in lights/light_panel_neutral
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapsaturation, $fresnelreflection, $worldimposter in glass/glasswindow_frosted
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_floor_metal_004b
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in anim_wp/framework/backpanels
[WARNING] UNSUPPORTED MATERIAL PARAMS: %nopaint in metal/metalgrate018
[3/12] Importing 13 models (reusing 0 existing)...
[3/12] Importing models... 38.4615 %
[3/12] Importing models... 76.9231 %
[3/12] Importing models... 100.0000 %
[4/12] Importing 82 textures (reusing 0 existing) and 61 materials (reusing 0 existing, 0 cannot be imported)...
[4/12] Importing textures... 12.1951 %
[4/12] Importing textures... 24.3902 %
[4/12] Importing textures... 36.5854 %
[4/12] Importing textures... 48.7805 %
[4/12] Importing textures... 60.9756 %
[4/12] Importing textures... 73.1707 %
[4/12] Importing textures... 85.3659 %
[4/12] Importing textures... 97.5610 %
[4/12] Importing textures... 100.0000 %
[5/12] Importing materials... 100.0000 %
[6/12] Building geometry...
[6/12] Building geometry... 38.7597 %
[6/12] Building geometry... 77.5194 %
[6/12] Building geometry... 93.0233 %
[6/12] Building geometry... 100.0000 %
[7/12] Building overlays...
[7/12] Building overlays... 100.0000 %
[8/12] Placing props...
[8/12] Placing props... 100.0000 %
[9/12] Optimizing props...
[10/12] Placing lights...
[10/12] Placing lights... 100.0000 %
[11/12] Importing skybox...
[ERROR] FAILED LOADING SKYBOX: materials/skybox/sky_day01_01lf.vmt
[12/12] Skipped sky origin
Done in 81.0817 s
Imported 645 solids (0 failed)
Imported 33 overlays (0 failed)
Imported 62 props (0 failed)
Imported 13 lights (0 failed)
Info: Total files 0 | Changed 0 | Failed 0
Writing userprefs: 'C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend' ok
Info: Preferences saved
```
You can open the console with `Window -> Toggle System Console` on Windows.

**Screenshots**
https://i.imgur.com/JUpoIaq.png
**Details (please complete the following information):**
 - OS: Windows 10
 - Blender Version: newest
 - Addon Version: newest
 - Did you download a release or build the addon yourself: downloaded a release
 - Related Game: Portal 2

**Additional context**

**Comment by DrPeeper228** [comment]
The cause is animation
