### ISSUE TITLE
all of props fail to import

### ISSUE THREAD

**Issue by Xephobia** [lasa01/io_import_vmf#17]
i decompiled cp_egypt_final_d from tf2 with bspsrc and when i import i get a lot of winerror 2 telling me that specific file was not found

**Comment by lasa01** [comment]
Have you specified a persistent models path in preferences? If you have,
make sure the path is absolute and valid. Could you enable the verbose
option, import it again and send the logs from Blender console?

**Comment by Xephobia** [comment]
well, with over 900 props it's hard, but it's like the same error over and over angain, so here a bit of the log :
`ERROR LOADING PROP: [WinError 2] Le fichier sp├®cifi├® est introuvable
Traceback (most recent call last):
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_vmf.py", line 185, in load
    self._load_prop(prop_entity, prop_collection)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_vmf.py", line 633, in _load_prop
    obj = self._qc_importer.load(name, collection)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_qc.py", line 170, in load
    return self.load_return_smd(name, collection).a
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_qc.py", line 158, in load_return_smd
    check=True
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\2.82\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\2.82\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\2.82\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier sp├®cifi├® est introuvable`
at the win error 2 part it's french text because my os is french, it tell "the specified file was not found"

**Comment by lasa01** [comment]
The addon dependency installation most likely failed. There's a bug in the install.ps1 script that fails downloading a required dependency. You will need to manually create the folder `io_import_vmf/io_import_vmf/bin/` before running the install script for it to work until I fix it.

**Comment by Xephobia** [comment]
ho ok

**Comment by lasa01** [comment]
Fixed the installation scripts.
