### ISSUE TITLE
enhanced mdl importer apear gray and cannot import

### ISSUE THREAD

**Issue by Xephobia** [lasa01/io_import_vmf#18]
using blender 2.82 with latest version of io_import_vmf (builded from source) and sourceIO

**Comment by lasa01** [comment]
Do they get imported but appear gray or does the import fail completely? In
any case, can you enable the verbose option, reimport and send logs from
the console?

**Comment by Xephobia** [comment]
no, i mean the import mdl enhanced is gray and cannot select it
![image](https://user-images.githubusercontent.com/28755060/80870582-a68e6b80-8ca7-11ea-9bd3-5be85b7b57e4.png)

**Comment by lasa01** [comment]
The .mdl importer uses SourceIO to import the mdl. You need to have it
installed and enabled.

**Comment by Xephobia** [comment]
i have it enabled
![image](https://user-images.githubusercontent.com/28755060/80870838-3e408980-8ca9-11ea-9524-1d0d34df8791.png)

**Comment by lasa01** [comment]
That's weird. Can you go to the scripting workspace in blender, type
`"SourceIO" in C.preferences.addons` to the console, press enter and send
what it returns.

**Comment by Xephobia** [comment]
i know i'm stupid but how?

**Comment by Xephobia** [comment]
ha yes, it return False

**Comment by Xephobia** [comment]
i think i found the prob, do i need to rename those?
![image](https://user-images.githubusercontent.com/28755060/80872369-c6c32800-8cb1-11ea-8f12-69d7ad7d9191.png)

**Comment by lasa01** [comment]
Yes, it should be named just SourceIO.

**Comment by Xephobia** [comment]
it works! thanks

**Comment by Xephobia** [comment]
darn
`Indexing game files...
Importing model...
Reading body parts  [####################] 1/1 Done    Building flex frame for Body
        Processing model ambulance_ref.smd with 0 flexes
Scanning, Body
Skipping ambulance_ref.smd cuz it's not a clamped mesh_data
Building mesh
Converting ambulance_ref model
Converting mesh  [####################] 16344/16344 Done    Mesh conversion took 1 sec
Building material amb_red...
Traceback (most recent call last):
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\__init__.py", line 889, in execute
    importer.load(splitext(relpath(self.filepath, root))[0], self.filepath, context.collection)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_mdl.py", line 178, in load
    importer.load(collection=collection)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_mdl.py", line 100, in load
    self.create_models()
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\SourceIO\source1\mdl\mdl2model.py", line 473, in create_models
    to_join.append(self.create_model(model, vtx_model))
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\SourceIO\source1\mdl\mdl2model.py", line 407, in create_model
    self.get_material(mat_name, self.mesh_obj)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_mdl.py", line 135, in get_material
    lambda: VMT(
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_vmt.py", line 1057, in load
    builder = _MaterialBuilder(self._vtf_importer, material_name, vmt_data(),
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\import_mdl.py", line 138, in <lambda>
    allow_patch=True,
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\deps\vmfpy\vmt.py", line 128, in __init__
    vdf_dict: dict = vdf.load(file, escaped=False)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\deps\vdf\__init__.py", line 189, in load
    return parse(fp, **kwargs)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_import_vmf\deps\vdf\__init__.py", line 106, in parse
    raise SyntaxError("vdf.parse: expected openning bracket (line %d)" % (idx + 1))
SyntaxError: vdf.parse: expected openning bracket (line 2)

location: <unknown location>:-1

location: <unknown location>:-1`

**Comment by Xephobia** [comment]
@lasa01

**Comment by lasa01** [comment]
I think this is a known issue, I'll fix it soon. No need to tag me, I
already get notified of replies to issues.

**Comment by lasa01** [comment]
Should be fixed now.
