### ISSUE TITLE
Sky cubemap not porting

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#21]
`ERROR LOADING SKYBOX: ERROR LOADING CUBEMAP: UNSUPPORTED HDR FORMAT 3
Traceback (most recent call last):
  File "C:\Users\leath\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_import_vmf\import_vmf.py", line 234, in load
    output_res=self.sky_resolution, context=context,
  File "C:\Users\leath\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_import_vmf\import_vmt.py", line 1100, in load_sky
    image = import_vtf.load_as_equi(skyname, textures, output_res, hdr=hdr)
  File "C:\Users\leath\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_import_vmf\import_vtf.py", line 68, in load_as_equi
    raise Exception(f"ERROR LOADING CUBEMAP: UNSUPPORTED HDR FORMAT {image_format}")
Exception: ERROR LOADING CUBEMAP: UNSUPPORTED HDR FORMAT 3`

Map is TF2's plr_hightower, heres the textures https://drive.google.com/file/d/1IFhQGIe0m0vMu4UkUyJ3PElsqj--x7N2/view?usp=sharing

**Comment by lasa01** [comment]
I can't find any information on that format, and the link is not working (no access). Can you also send the .vmt files (if you didn't already)?

**Comment by LethalDumpster** [comment]
Sorry about that. Google drive updated their UI, and made shared links private by default now, like wtf!?
There, I set it to public. Same link. Its the VMTs and VTFs.

**Comment by lasa01** [comment]
The texture is probably not really HDR since the same texture is marked as base texture and hdr base texture. Now unknown formats are assumed to be not really HDR and this should be fixed.
