### ISSUE TITLE
Importing models stops half way.

### ISSUE THREAD

**Issue by Electrognome** [lasa01/io_import_vmf#46]
Did everything according to your youtube tutorial.
Importing stops at 13% with an error: 

Python: Traceback (most recent call last):
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_qc.py", line 346, in _load
    fake_smd = FakeSmd.from_bst(SmdImporterWrapper.smd)
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_qc.py", line 38, in from_bst
    raise Exception("nothing was imported by Blender Source Tools")
Exception: nothing was imported by Blender Source Tools

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\__init__.py", line 737, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_vmf.py", line 160, in load
    self._qc_importer.load_all()
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_qc.py", line 232, in load_all
    self._load(name, staged)
  File "\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_qc.py", line 348, in _load
    raise Exception(f"Error importing {name}: {err}")
Exception: Error importing models/anubis/structures/pillar01: nothing was imported by Blender Source Tools

location: <unknown location>:-1

I also get a bunch of [WARNING] MATERIAL IS INVALID and [WARNING] UNSUPPORTED MATERIAL PARAMS before importing models starts.

**Comment by lasa01** [comment]
Which game and map is this?

**Comment by lasa01** [comment]
Closing because of inactivity.
