### ISSUE TITLE
Can't import a specific map (gm_blood_gulch_v3)

### ISSUE THREAD

**Issue by phoondos** [lasa01/io_import_vmf#65]
`Python: Traceback (most recent call last):
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 92, in _parse_float
    return float(value)
ValueError: could not convert string to float: '187,5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\__init__.py", line 744, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_vmf.py", line 139, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 774, in __init__
    entity_inst = self._parse_custom(VMFLightEntity, "entity (light)", entity, self.fs)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 390, in __init__
    self.fifty_percent_distance = self._parse_float_str("_fifty_percent_distance", data)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 100, in _parse_float_str
    return self._parse_float(name, value)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 94, in _parse_float
    raise VMFParseException(f"{name} is not a valid float", self._context)
vmfpy.VMFParseException: VMF parsing failed: entity (light) (id 73896) _fifty_percent_distance is not a valid float

location: <unknown location>:-1`

**Comment by lasa01** [comment]
Seems like the vmf file is invalid. Where did you get it from? You can probably fix it by replacing `187,5` with `187.5`.

**Comment by phoondos** [comment]
Got the map from the Garry's Mod workshop, and decomped it using BSPsrc. How can I replace these values?

**Comment by lasa01** [comment]
It's just a text file, you can open it in Notepad and use Edit -> Replace.

**Comment by phoondos** [comment]
I don't have a file called vmfpy_init_.py where it says it is... I don't know what file I should be editing

**Comment by phoondos** [comment]
Ohhhhh, I understand. Edit the actual VMF. Sorry for bothering you, I'll try this right now

**Comment by phoondos** [comment]
It worked, but there's some geometry missing and for some reason, the materials aren't being applied despite making a VPK with the materials, sounds, and models included and setting the addon to read it as a VPK.

**Comment by lasa01** [comment]
Make sure the VPK has the correct directory structure, it should have a materials and models directory directly inside it. Also make sure you have selected the correct game. If the materials are part of the map, you should probably use the embedded files directory in the VMF import dialog instead, just set it to the path of the directory containing the required assets (in the same directory structure as above). If some geometry is missing, you can try decreasing the brush epsilon in the import dialog.

**Comment by lasa01** [comment]
Closing because of inactivity.
