### ISSUE TITLE
Support Needed for Source Filmmaker

### ISSUE THREAD

**Issue by GeoDoesAnimations** [lasa01/io_import_vmf#71]
Heyo. Im just here because this addon needs some support for SFM maps, since ive been trying to port them but this addon apparently doesnt support it or something and just gives me a big long error. I will send proof if needed.

**Comment by ArclightReflex** [comment]
it supports any kind of source 1 map which can be decompiled.
so does sfm.
you can enable verbose to see more detail.

**Comment by GeoDoesAnimations** [comment]
yeah but uhh

the UV maps dont save

**Comment by ChristianSoldier** [comment]
I have the same problem.  It only imports the base geometry, and not any of the materials/textures/props.

**Comment by ArclightReflex** [comment]
You don't get what I mean.....It only imports the base geometry not because it's a SFM map(SFM map is just a normal source map which has no difference)it because something wrong happened when importing.
Just open the Verbose to see more error message for detail and fix it then it will be fine.

I met various conditions when trying to import custom map from gmod and SFM , but most of them can find a simple solution.

**Comment by ArclightReflex** [comment]
I imported about ten bigger maps and in each of them I met some error cause failure to load some (or all) models of materials
Yeah I must say there are many bugs when loading custom map.
many unexpected problem may happened.
but it's not a hard thing to fix. 
Again,  enable Verbose and see the error message.

**Comment by ArclightReflex** [comment]
I imported about ten bigger maps and in each of them I met some error cause failure to load some (or all) models or materials
Yeah I must say there are many bugs when loading custom map.
many unexpected problem may happened.
but it's not a hard thing to fix.
Again, enable Verbose and see the error message.

**Comment by ChristianSoldier** [comment]
When I enable Verbose, it says that the file for the skybox wasn't found.  But when I checked the location it was looking in, it WAS there.  It also says the prop models "weren't imported", and a bunch of other things about the importer itself.

**Comment by ArclightReflex** [comment]
see the call trace information besides "weren't imported"
that's the thing we needed.
you can copy and paste it here.I will see for you.

**Comment by ChristianSoldier** [comment]
Note: I know nothing of how the code of the addon works.

Here's an example of a couple stuff it showed me:

[ERROR] LOADING PROP FAILED: model models/props_farm/drain_pipe001 hasn't been imported
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 279, in load
    self._load_prop(prop_entity, context, prop_collection)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 798, in _load_prop
    obj = self._qc_importer.get_unique(name, collection, context)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 427, in get_unique
    return self.get_unique_smd(name, collection, context).a
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 408, in get_unique_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models/props_farm/drain_pipe001 hasn't been imported
[ERROR] LOADING PROP FAILED: model models/props_gameplay/door_slide_large_frame hasn't been imported
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 279, in load
    self._load_prop(prop_entity, context, prop_collection)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 798, in _load_prop
    obj = self._qc_importer.get_unique(name, collection, context)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 427, in get_unique
    return self.get_unique_smd(name, collection, context).a
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 408, in get_unique_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models/props_gameplay/door_slide_large_frame hasn't been imported
[ERROR] LOADING PROP FAILED: model models/props_2fort/window004 hasn't been imported
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 279, in load
    self._load_prop(prop_entity, context, prop_collection)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 798, in _load_prop
    obj = self._qc_importer.get_unique(name, collection, context)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 427, in get_unique
    return self.get_unique_smd(name, collection, context).a
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 408, in get_unique_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models/props_2fort/window004 hasn't been imported
[ERROR] LOADING PROP FAILED: model models/props_2fort/window004 hasn't been imported
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 279, in load
    self._load_prop(prop_entity, context, prop_collection)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 798, in _load_prop
    obj = self._qc_importer.get_unique(name, collection, context)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 427, in get_unique
    return self.get_unique_smd(name, collection, context).a
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 408, in get_unique_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models/props_2fort/window004 hasn't been imported
[ERROR] LOADING PROP FAILED: model models/props_badlands/badlands_rails hasn't been imported
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 279, in load
    self._load_prop(prop_entity, context, prop_collection)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 798, in _load_prop
    obj = self._qc_importer.get_unique(name, collection, context)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 427, in get_unique
    return self.get_unique_smd(name, collection, context).a
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_qc.py", line 408, in get_unique_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models/props_badlands/badlands_rails hasn't been imported
[8/12] Placing props... 100.0000 %
[9/12] Optimizing props...
[10/12] Placing lights...
[10/12] Placing lights... 100.0000 %
[11/12] Importing skybox...
[ERROR] FAILED LOADING SKYBOX: materials/skybox/sky_badlands_01lf.vmt
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmf.py", line 348, in load
    output_res=self.sky_resolution, context=context,
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\import_vmt.py", line 1228, in load_sky
    sky_vmt = vmt.VMT(fs.open_file_utf8(f"{skyname}{suffix}.vmt"), fs)
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 170, in open_file_utf8
    return TextIOWrapper(cast(IO[bytes], self.open_file(path)), encoding='utf-8')
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_vmf\deps\vmfpy\fs.py", line 166, in open_file
    raise FileNotFoundError(path)
FileNotFoundError: materials/skybox/sky_badlands_01lf.vmt
[12/12] Skipped sky origin
Done in 32.1258 s
Imported 3236 solids (0 failed)
Imported 119 overlays (0 failed)
Imported 0 props (718 failed)
Imported 52 lights (0 failed)

**Comment by ArclightReflex** [comment]
it seems like crowbar cmd or game indexing didn't work correctly.
can you give the name is the map?
I will try it on my computer to exclude other possibility of erroring.

**Comment by ArclightReflex** [comment]
it seems like crowbar cmd or game indexing didn't work correctly.
can you give the name of the map?
I will try it on my computer to exclude other possibility of erroring.

**Comment by ChristianSoldier** [comment]
"arena_badlands"
It was in the folder "tf".

**Comment by GeoDoesAnimations** [comment]
what have i started.

**Comment by ArclightReflex** [comment]
Unlike some custom maps,I didn't meet a single error when importing cp_badlands in SFM folder.
https://sta.sh/01h4d8eye7d0
https://sta.sh/04lx1xs2ozw
Are you do some steps wrong?Like forgeting to set game directory?Or don't have IO permission?

**Comment by lasa01** [comment]
Closing because of inactivity.
