### ISSUE TITLE
vmf parsing failure

### ISSUE THREAD

**Issue by gyorio** [lasa01/io_import_vmf#72]
`Indexing game files...
Indexing done in 1.1513142585754395 s
Started importing VMF 'C:\Users\efrie\Desktop\assests\maps\levels\hl2\vmfs\leak\john\city17\d1_garage_01\d1_garage_01_32.vmf'
[1/12] Parsing map...
Python: Traceback (most recent call last):
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\__init__.py", line 744, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\import_vmf.py", line 139, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 736, in __init__
    self.world: VMFWorldEntity = self._parse_custom(VMFWorldEntity, "world", world_dict, self.fs)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 705, in __init__
    super().__init__(data, fs)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 699, in __init__
    self.solids.append(self._parse_custom(VMFSolid, "solid", solid, self.fs))
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 687, in __init__
    self.sides.append(self._parse_custom(VMFSide, "side", side, self.fs))
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 665, in __init__
    self.dispinfo = self._parse_custom(VMFDispInfo, "dispinfo", dispinfo_dict)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 621, in __init__
    allowed_verts_dict = self._parse_dict("allowed_verts", data)
  File "C:\Users\efrie\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 115, in _parse_dict
    raise VMFParseException(f"{name} doesn't exist", self._context)
vmfpy.VMFParseException: VMF parsing failed: world (id 0) solid (id 162049) side (id 2753) dispinfo allowed_verts doesn't exist

location: <unknown location>:-1`

**Comment by gyorio** [comment]
Note: the map vmf is from the wc mappack LEAK. When I imported a RETAIL vmf it succeeded just fine.
