### ISSUE TITLE
The Addon won't install, even when the io_import_vmf.zip is downloaded, not the source code. (Using Blender 2.9)

### ISSUE THREAD

**Issue by AverageGithubEnjoyer** [lasa01/io_import_vmf#93]
**Describe the bug**
When I have downloaded the .zip file, I get an error saying "no module named 'vmfpy'"

The way I have installed the addon:
1. Download the latest io_import_vmf.zip
2. Open Blender, go to Preferences and install the modules.
3. Close Blender (version 2.90.1)
4. Go to the io_import_vmf.zip 
5. Extract the .zip file.
6. Copy the folder "io import vmf"
7. Paste it in "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons"

**Expected behavior**
After going into Blender, then Preferences, I had expected the addon to work when i checked the tick box. Smooth sailing from there.

**Logs**
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_import_vmf\__init__.py", line 11, in <module>
    from vmfpy.fs import VMFFileSystem  # noqa: 402
ModuleNotFoundError: No module named 'vmfpy'

```

**Details (please complete the following information):**
 - OS: Windows 10 Home Single Language 64 bit.
 - Blender Version: 2.90.1
 - Addon Version: 0.6.4
 - Related Game: CS:GO

**Additional context**
I did not donwload the source code from the releases. I have downloaded io_import_vmf-v0.6.4.zip .

**Comment by AverageGithubEnjoyer** [comment]
EDIT: I have properly read the instructions, and have been able to fix my problem. It was my error. Sorry, everyone.
