### ISSUE TITLE
Py Error when import

### ISSUE THREAD

**Issue by Pralexi** [lasa01/io_import_vmf#96]
i get this when i want to import a csgo map into blender if you can help ty ^^.

Python: Traceback (most recent call last):
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\__init__.py", line 748, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\import_vmf.py", line 140, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 736, in __init__
    self.world: VMFWorldEntity = self._parse_custom(VMFWorldEntity, "world", world_dict, self.fs)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 705, in __init__
    super().__init__(data, fs)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 699, in __init__
    self.solids.append(self._parse_custom(VMFSolid, "solid", solid, self.fs))
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 687, in __init__
    self.sides.append(self._parse_custom(VMFSide, "side", side, self.fs))
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 636, in __init__
    self.plane: VMFPlane = self._parse_custom_str(VMFPlane.parse, "plane", data)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 145, in _parse_custom_str
    return self._parse_custom(parser, name, value)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 138, in _parse_custom
    return parser(*args)
  File "C:\Users\Pralexio\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 520, in parse
    raise VMFParseException("plane syntax is invalid")
vmfpy.VMFParseException: VMF parsing failed: world (id 1) solid (id 16) side (id 19) plane plane syntax is invalid

location: <unknown location>:-1

**Comment by Pralexi** [comment]
(i have tried different version of blender)

**Comment by lasa01** [comment]
Seems like the vmf file is broken/corrupted. Can you send the vmf file so I
can verify it?

**Comment by Pralexi** [comment]
[dust.zip](https://github.com/lasa01/io_import_vmf/files/7229678/dust.zip)

**Comment by Pralexi** [comment]
i have tried different map and i got the same issue

**Comment by Pralexi** [comment]
i got the same issues with a map from gmod (gm_construct)

**Comment by Pralexi** [comment]
my bad forget that i was using the wrong version of bspsource its ok all work ^^ ty for your help.
